name: Package Excalibur with Pyinstaller

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - { os: macos-latest, arch: x64, name: macos-latest }
          - { os: ubuntu-latest, arch: x64, name: ubuntu-latest }
          - { os: windows-latest, arch: x64, name: windows-latest }
          - { os: windows-latest, arch: ia32, name: windows-latest-32 }


    steps:
        - uses: actions/checkout@v1
        - name: Set up Python 3.8
          uses: actions/setup-python@v1
          with:
            python-version: 3.8
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pyinstaller
        - name: build with pyinstaller
          run: |
            pyi-makespec --paths=excalibur/executors/celery_executor.py arthur.py
            pyinstaller --onefile --add-data "excalibur/www/templates:excalibur/www/templates" --add-data "excalibur/www/static:excalibur/www/static" --add-data "excalibur/config_templates:excalibur/config_templates" arthur.py
          if: matrix.os == 'windows-latest'
          run: |
            pyi-makespec --paths=excalibur/executors/celery_executor.py arthur.py
            pyinstaller --onefile --add-data "excalibur/www/templates;excalibur/www/templates" --add-data "excalibur/www/static;excalibur/www/static" --add-data "excalibur/config_templates;excalibur/config_templates" arthur.py
              

 #  - uses: actions/upload-artifact@v2
 #     with:
 #       name: name-of-artifact
 #       path: src/dist/

